### ISSUE TITLE
GreenField or BrownField

### ISSUE THREAD

**Issue by MitchSchulz** [MicrosoftDocs/architecture-center.de-de#4]
Hallo, 
ich bin über eine Link relativ direkt auf diese Seite gekommen. Gleich am Anfang der zentralen Grafik steht die Auswahl zwischen "Greenfield" oder "Brownfield". Was diese Auswahl bedeutet ist jedoch nicht erläutert. So ist das nicht sehr hilfreich, wenn man gleich am Anfang "aussteigt".

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 510808e8-db5d-6b07-9a04-6edb743a2dfc
* Version Independent ID: 20d098aa-ef31-cb26-d677-765cfc9a7164
* Content: [Entscheidungsstruktur für Azure-Computedienste - Azure Application Architecture Guide](https://docs.microsoft.com/de-de/azure/architecture/guide/technology-choices/compute-decision-tree)
* Content Source: [docs/guide/technology-choices/compute-decision-tree.md](https://github.com/microsoftdocs/architecture-center.de-de/blob/live/docs/guide/technology-choices/compute-decision-tree.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by CeciAc** [comment]
Hallo, @MitchSchulz 

Vielen Dank für Ihr Feedback. 

Ihre Kommentare werden aktuell von uns geprüft. Wir melden uns bald bei Ihnen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @ishasahni1 
Can you please update the status of this one?

**Comment by ishasahni1** [comment]
@CeciAc this repo has been re onboarded and in localization, so I will update by next week once this article is localized will update this issue.

**Comment by ishasahni1** [comment]
@MitchSchulz this issue has been addressed now. Apologies for the delay this repo had to be re-onboarded on our end due to certain structure changes.
https://docs.microsoft.com/de-de/azure/architecture/guide/technology-choices/compute-decision-tree
